version: "3.9"

services:
  redis-master:
    build: .
    container_name: redis-master
    environment:
      REDIS_ROLE: master
      REDIS_PORT: 6379
      DATA_DIR: /data
    ports:
      - "6379:6379"
    volumes:
      - redis-master-data:${DATA_DIR}

  redis-replica:
    build: .
    depends_on:
      - redis-master
    environment:
      REDIS_ROLE: slave
      REDIS_MASTER_HOST: redis-master
      REDIS_MASTER_PORT: 6379
      REDIS_PORT: 6379
    ports:
      - "6380-6390:6379"

volumes:
  redis-master-data:
    driver: local